CREATE SEQUENCE users_seq START WITH 1 INCREMENT BY 1;

CREATE SEQUENCE team_seq START WITH 1 INCREMENT BY 1;

CREATE SEQUENCE task_status_seq START WITH 1 INCREMENT BY 1;

CREATE SEQUENCE task_seq START WITH 1 INCREMENT BY 1;

CREATE SEQUENCE task_pause_seq START WITH 1 INCREMENT BY 1;

CREATE SEQUENCE tags_seq START WITH 1 INCREMENT BY 1;

CREATE SEQUENCE task_tags_seq START WITH 1 INCREMENT BY 1;